#!/usr/bin/env bash

# 
# XCode
#
if [ -z `which gcc` ]; then
	echo "Error: XCode command line tools not installed!"
	exit 1
fi

#
# Homebrew
# 
if [ -z `which brew` ]; then
	echo "Installing Homebrew..."
    ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
fi

echo "Update Homebrew..."
  brew update

#
# Projects directory
#
if [ ! -e "$HOME/Projects" ]; then
  echo "Create $HOME/Projects"
    mkdir $HOME/Projects
fi

#
# Install git
#
if [ -z `which git` ]; then
  echo "Install git..."
    brew install git
fi
  
# 
# Clone the dev setup tools
# 
if [ ! -e "$HOME/Projects/osx-dev-setup" ]; then
  echo "Clone the dev setup tools..."
    cd $HOME/Projects
    git clone https://github.com/markosamuli/osx-dev-setup.git
fi

# 
# Fix Applications directory permissions
#
echo "Fix Applications directory permissions..."
sudo chown `whoami` /Applications

#
# Ready, print instructions
#
echo "Install applications:"
echo "cd $HOME/Projects/osx-dev-setup"
echo "./setup-apps"