#!/usr/bin/env bash

# 
# Fix Applications directory permissions
#
sudo chown `whoami` /Applications

#
# Bundler
#
if [ -z `which bundle` ]; then
  echo "Install bundler..."
  sudo gem install bundler
fi

echo "Install soloist & and other required gems..."
	bundle
  
echo "Run soloist..."
  bundle exec soloist
