name             'markosamuli-osx-apps'
maintainer       'Marko Samuli Kirves'
license          'MIT'
description      'Recipes to install common OSX applications on Mountain Lion'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-osx-base'
depends          'sprout-osx-settings'
depends          'sprout-osx-apps'
depends          'dmg'